# -*- coding: utf-8 -*-
"""
stance_knowledge.py

Simplest possible version of the "keyword-triggered knowledge under a fixed
stance" feature discussed for the parent_child scenario:

  1. If the user's message matches a keyword in the CURRENT SPEAKING AGENT'S
     stance-specific topic cards -> use that card.
  2. Otherwise -> use that stance's generic fallback card.

Both paths are static, local dict lookups. No network calls, no vector
search, no LLM call — this is intentional: it keeps latency at zero and
keeps every possible output fully pre-written and auditable (same
"assignment-layer determinism" principle as PHASE_PROMPTS / STANCE_PROMPTS).

Data files: background_templates/stance_knowledge/{scenario_type}.json
(one file per scenario, e.g. parent_child.json, employment.json)
Each file's structure (no outer scenario_type key — the filename IS the
scenario type, matching the same convention already used for
scenario_templates/ and background_templates/):
  {
    "<stance>": {
      "topic_cards": [
        {
          "id": "...", "keywords": [...], "text": {"zh":..., "en":...},
          "source": "...", "source_type": "academic|government|institutional",
          "related_cards": ["<other card id>", ...]
        }, ...
      ],
      "generic_fallback": {"zh":..., "en":..., "source": "...", "source_type": "..."}
    }, ...
  }

Current coverage (generated by build_stance_knowledge.py):
  parent_child.json: 3 stances x 5 topic cards + 3 generic fallbacks = 18 cards
  employment.json:   3 stances x 5 topic cards + 3 generic fallbacks = 18 cards
"""
from __future__ import annotations

import json
import os
from typing import Optional

from lang_utils import normalize_lang, pick, header

STANCE_KNOWLEDGE_DIR_DEFAULT = os.path.join("background_templates", "stance_knowledge")


def load_stance_knowledge(dir_path: str = STANCE_KNOWLEDGE_DIR_DEFAULT) -> dict:
    """
    Loads background_templates/stance_knowledge/{scenario_type}.json — one
    file per scenario (parent_child.json, employment.json), matching the
    same split-file convention already used for scenario_templates/ and
    background_templates/. Missing scenario files are skipped silently
    (that scenario just has no knowledge base, same as before).

    Returns the same merged shape the rest of this module expects:
        {"<scenario_type>": {"<stance>": {...}, ...}, ...}
    """
    knowledge = {}
    if not os.path.isdir(dir_path):
        return knowledge
    for fname in os.listdir(dir_path):
        if not fname.endswith(".json"):
            continue
        scenario_type = fname[:-5]  # strip ".json"
        with open(os.path.join(dir_path, fname), "r", encoding="utf-8-sig") as f:
            knowledge[scenario_type] = json.load(f)
    return knowledge


def _match_topic_card(user_message: str, topic_cards: list, lang: str) -> Optional[dict]:
    if not user_message:
        return None
    msg_lower = user_message.lower()
    for card in topic_cards:
        for kw in card.get("keywords", []):
            if kw.lower() in msg_lower:
                return card
    return None


def _find_card_by_id(scenario_cfg: dict, card_id: str) -> Optional[dict]:
    """Searches all stances within a scenario for a topic card with this id
    (related_cards can point across stances, not just within the same one)."""
    for stance_cfg in scenario_cfg.values():
        for c in stance_cfg.get("topic_cards", []):
            if c.get("id") == card_id:
                return c
    return None


def get_stance_knowledge_block(
    scenario_type: str,
    stance: Optional[str],
    user_message: str,
    lang: str = "zh",
    knowledge: Optional[dict] = None,
    knowledge_dir: str = STANCE_KNOWLEDGE_DIR_DEFAULT,
    include_header: bool = True,
    include_related: bool = False,
) -> str:
    """
    Returns a ready-to-inject text block for the CURRENT speaking agent
    (identified by its stance), or "" if this scenario/stance has no
    knowledge base defined (e.g. employment, or stances not yet covered).

    knowledge: pass a pre-loaded dict to avoid re-reading the file every
    turn (recommended — load once in main(), reuse across the session).

    include_related: when True and a specific topic card was matched
    (not the generic fallback), also appends the one-hop related cards
    listed in that card's `related_cards` field — a lightweight stand-in
    for GraphRAG's multi-hop retrieval, implemented as plain dict lookups
    with zero added latency. Off by default; turn on only when you want
    to go a level deeper (e.g. the same topic keeps coming up across turns).
    """
    if not stance:
        return ""
    lang = normalize_lang(lang)

    if knowledge is None:
        knowledge = load_stance_knowledge(knowledge_dir)

    scenario_cfg = knowledge.get(scenario_type, {})
    stance_cfg = scenario_cfg.get(stance)
    if not stance_cfg:
        return ""

    card = _match_topic_card(user_message, stance_cfg.get("topic_cards", []), lang)
    if card is not None:
        text_field = card["text"]
        source = card.get("source", "")
    else:
        fallback = stance_cfg.get("generic_fallback")
        if not fallback:
            return ""
        text_field = {"zh": fallback.get("zh", ""), "en": fallback.get("en", "")}
        source = fallback.get("source", "")

    body = pick(text_field, lang)

    if not include_header:
        return body

    label = "背景知识（仅供参考）" if lang == "zh" else "BACKGROUND KNOWLEDGE (for reference only)"
    src_label = "来源" if lang == "zh" else "Source"
    block = f"=== {label} ===\n{body}\n({src_label}: {source})"

    if include_related and card is not None and card.get("related_cards"):
        related_label = "相关背景" if lang == "zh" else "Related background"
        related_parts = []
        for rel_id in card["related_cards"]:
            rel_card = _find_card_by_id(scenario_cfg, rel_id)
            if rel_card:
                rel_body = pick(rel_card["text"], lang)
                rel_source = rel_card.get("source", "")
                related_parts.append(f"- {rel_body} ({src_label}: {rel_source})")
        if related_parts:
            block += f"\n\n[{related_label}]\n" + "\n".join(related_parts)

    return block


if __name__ == "__main__":
    knowledge = load_stance_knowledge()

    print("--- hit a topic card (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "parent_centered", "我们俩总是有冲突", lang="zh", knowledge=knowledge))

    print("\n--- no keyword match -> generic fallback (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "child_centered", "他说想学做饭", lang="zh", knowledge=knowledge))

    print("\n--- English, topic card (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "relationship_centered", "I don't think he trusts me anymore", lang="en", knowledge=knowledge))

    print("\n--- employment scenario now has content too ---")
    print(get_stance_knowledge_block(
        "employment", "stability_centered", "我担心公司要裁员了", lang="zh", knowledge=knowledge))

    print("\n--- one-hop related_cards expansion ---")
    print(get_stance_knowledge_block(
        "employment", "growth_centered", "感觉这份工作技能都要跟不上了", lang="zh",
        knowledge=knowledge, include_related=True))

    print("\n--- scenario/stance combo with no cfg -> empty string (sanity check) ---")
    print(repr(get_stance_knowledge_block("employment", "nonexistent_stance", "anything", knowledge=knowledge)))
