# -*- coding: utf-8 -*-
"""
stance_knowledge.py

Simplest possible version of the "keyword-triggered knowledge under a fixed
stance" feature discussed for the parent_child scenario:

  1. If the user's message matches a keyword in the CURRENT SPEAKING AGENT'S
     stance-specific topic cards -> use that card.
  2. Otherwise -> use that stance's generic fallback card.

Both paths are static, local dict lookups. No network calls, no vector
search, no LLM call — this is intentional: it keeps latency at zero and
keeps every possible output fully pre-written and auditable (same
"assignment-layer determinism" principle as PHASE_PROMPTS / STANCE_PROMPTS).

Data files: background_templates/stance_knowledge/{scenario_type}.json
(one file per scenario, e.g. parent_child.json, employment.json)
Each file's structure (no outer scenario_type key — the filename IS the
scenario type, matching the same convention already used for
scenario_templates/ and background_templates/):
  {
    "<stance>": {
      "topic_cards": [
        {
          "id": "...", "keywords": [...], "text": {"zh":..., "en":...},
          "source": "...", "source_type": "academic|government|institutional",
          "related_cards": ["<other card id>", ...]
        }, ...
      ],
      "generic_fallback": {"zh":..., "en":..., "source": "...", "source_type": "..."}
    }, ...
  }

Current coverage (generated by build_stance_knowledge.py):
  parent_child.json: 3 stances x 5 topic cards + 3 generic fallbacks = 18 cards
  employment.json:   3 stances x 5 topic cards + 3 generic fallbacks = 18 cards
"""
from __future__ import annotations

import json
import os
import re
from typing import List, Optional

from lang_utils import normalize_lang, pick, header

STANCE_KNOWLEDGE_DIR_DEFAULT = os.path.join("background_templates", "stance_knowledge")

_CJK_RE = re.compile(r"[\u4e00-\u9fff]")
_STANCE_ID_PREFIXES = (
    "growth_",
    "stability_",
    "life_",
    "child_",
    "parent_",
    "relationship_",
)


def _has_cjk(text: str) -> bool:
    return bool(_CJK_RE.search(text or ""))


def _keyword_for_lang(kw: str, lang: str) -> bool:
    """Split bilingual keyword lists for UI: en → Latin-ish, zh → CJK-containing."""
    kw = (kw or "").strip()
    if not kw:
        return False
    cjk = _has_cjk(kw)
    if normalize_lang(lang) == "zh":
        return cjk
    return not cjk


def _soft_keyword_hit(msg_lower: str, kw_lower: str) -> bool:
    """Allow a short hint to match a longer keyword phrase.

    Hard match remains `kw in msg`. Soft match is the reverse (`msg in kw`) with
    guardrails so single English tokens like "job" / "change" do not fire.
    """
    if not msg_lower or not kw_lower or msg_lower not in kw_lower:
        return False
    if _has_cjk(msg_lower):
        return len(msg_lower) >= 2
    tokens = [t for t in re.split(r"\s+", msg_lower) if t]
    return len(tokens) >= 2 and len(msg_lower) >= 5


def _humanize_card_id(card_id: str) -> str:
    title = card_id or ""
    for prefix in _STANCE_ID_PREFIXES:
        if title.startswith(prefix):
            title = title[len(prefix) :]
            break
    return title.replace("_", " ").strip()


def load_stance_knowledge(dir_path: str = STANCE_KNOWLEDGE_DIR_DEFAULT) -> dict:
    """
    Loads background_templates/stance_knowledge/{scenario_type}.json — one
    file per scenario (parent_child.json, employment.json), matching the
    same split-file convention already used for scenario_templates/ and
    background_templates/. Missing scenario files are skipped silently
    (that scenario just has no knowledge base, same as before).

    Returns the same merged shape the rest of this module expects:
        {"<scenario_type>": {"<stance>": {...}, ...}, ...}
    """
    knowledge = {}
    if not os.path.isdir(dir_path):
        return knowledge
    for fname in os.listdir(dir_path):
        if not fname.endswith(".json"):
            continue
        scenario_type = fname[:-5]  # strip ".json"
        with open(os.path.join(dir_path, fname), "r", encoding="utf-8-sig") as f:
            knowledge[scenario_type] = json.load(f)
    return knowledge


def _match_topic_card(user_message: str, topic_cards: list, lang: str) -> Optional[dict]:
    if not user_message:
        return None
    msg_lower = user_message.lower().strip()
    # Pass 1: classic "keyword appears in the message".
    for card in topic_cards:
        for kw in card.get("keywords", []):
            if kw.lower() in msg_lower:
                return card
    # Pass 2: soft — short setup hints / partial phrases against longer keywords.
    for card in topic_cards:
        for kw in card.get("keywords", []):
            if _soft_keyword_hit(msg_lower, kw.lower()):
                return card
    return None


def preview_matched_card(
    scenario_type: str,
    stance: Optional[str],
    hint: str,
    lang: str = "en",
    knowledge: Optional[dict] = None,
    knowledge_dir: str = STANCE_KNOWLEDGE_DIR_DEFAULT,
) -> dict:
    """
    Preview which topic card a setup hint would bind for UI tags.
    Does NOT use generic_fallback (matches assemble preload: miss → empty).

    Tags are topic identity (+ optional source_type), not match-keyword synonyms.
    The topic label prefers a language-filtered keyword for display, else a
    humanized card id — keywords themselves stay on card.keywords only.
    """
    hint = (hint or "").strip()
    lang = normalize_lang(lang)
    if not scenario_type or not stance or not hint:
        return {"matched": False, "fallback": False, "tags": [], "card": None}

    if knowledge is None:
        knowledge = load_stance_knowledge(knowledge_dir)
    scenario_cfg = (knowledge or {}).get(scenario_type, {}) or {}
    stance_cfg = scenario_cfg.get(stance) if isinstance(scenario_cfg, dict) else None
    if not isinstance(stance_cfg, dict):
        return {"matched": False, "fallback": False, "tags": [], "card": None}

    card = _match_topic_card(hint, stance_cfg.get("topic_cards", []) or [], lang)
    if not card:
        return {"matched": False, "fallback": False, "tags": [], "card": None}

    keywords = list(card.get("keywords") or [])
    lang_keywords = [kw for kw in keywords if _keyword_for_lang(kw, lang)]
    display_keywords = lang_keywords or keywords

    # UI tags = topic identity (+ optional provenance). Match keywords stay in
    # card.keywords for debugging — they must NOT be dumped as tag chips.
    humanized = _humanize_card_id(str(card.get("id") or ""))
    topic_label = (lang_keywords[0] if lang_keywords else "") or humanized or str(card.get("id") or "")
    tags: List[dict] = [{"id": f"topic:{card.get('id')}", "label": topic_label}]
    source_type = (card.get("source_type") or "").strip()
    if source_type:
        tags.append({"id": f"source:{source_type}", "label": source_type})

    return {
        "matched": True,
        "fallback": False,
        "tags": tags,
        "card": {
            "id": card.get("id"),
            "title": topic_label,
            "keywords": display_keywords,
            "keywords_all": keywords,
            "source_type": source_type or card.get("source_type"),
        },
    }


def _find_card_by_id(scenario_cfg: dict, card_id: str) -> Optional[dict]:
    """Searches all stances within a scenario for a topic card with this id
    (related_cards can point across stances, not just within the same one)."""
    for stance_cfg in scenario_cfg.values():
        for c in stance_cfg.get("topic_cards", []):
            if c.get("id") == card_id:
                return c
    return None


def peek_matched_card_id(
    scenario_type: str,
    stance: Optional[str],
    user_message: str,
    lang: str = "zh",
    knowledge: Optional[dict] = None,
    knowledge_dir: str = STANCE_KNOWLEDGE_DIR_DEFAULT,
) -> Optional[str]:
    """Lightweight probe: return the id of the topic card `user_message` WOULD
    hit for this scenario/stance, or None (no keyword match, or no
    scenario/stance/knowledge base). Builds no text and never falls back to the
    generic card — it uses the exact same matcher as get_stance_knowledge_block,
    so callers can cheaply decide *whether* to expand related cards (and track
    repeat hits) before paying to assemble the full block.
    """
    if not stance or not user_message:
        return None
    lang = normalize_lang(lang)
    if knowledge is None:
        knowledge = load_stance_knowledge(knowledge_dir)
    stance_cfg = knowledge.get(scenario_type, {}).get(stance)
    if not stance_cfg:
        return None
    card = _match_topic_card(user_message, stance_cfg.get("topic_cards", []), lang)
    return card.get("id") if card else None


def get_stance_knowledge_block(
    scenario_type: str,
    stance: Optional[str],
    user_message: str,
    lang: str = "zh",
    knowledge: Optional[dict] = None,
    knowledge_dir: str = STANCE_KNOWLEDGE_DIR_DEFAULT,
    include_header: bool = True,
    include_related: bool = False,
) -> str:
    """
    Returns a ready-to-inject text block for the CURRENT speaking agent
    (identified by its stance), or "" if this scenario/stance has no
    knowledge base defined (e.g. employment, or stances not yet covered).

    knowledge: pass a pre-loaded dict to avoid re-reading the file every
    turn (recommended — load once in main(), reuse across the session).

    include_related: when True and a specific topic card was matched
    (not the generic fallback), also appends the one-hop related cards
    listed in that card's `related_cards` field — a lightweight stand-in
    for GraphRAG's multi-hop retrieval, implemented as plain dict lookups
    with zero added latency. Off by default; turn on only when you want
    to go a level deeper (e.g. the same topic keeps coming up across turns).
    """
    if not stance:
        return ""
    lang = normalize_lang(lang)

    if knowledge is None:
        knowledge = load_stance_knowledge(knowledge_dir)

    scenario_cfg = knowledge.get(scenario_type, {})
    stance_cfg = scenario_cfg.get(stance)
    if not stance_cfg:
        return ""

    card = _match_topic_card(user_message, stance_cfg.get("topic_cards", []), lang)
    if card is not None:
        text_field = card["text"]
        source = card.get("source", "")
    else:
        fallback = stance_cfg.get("generic_fallback")
        if not fallback:
            return ""
        text_field = {"zh": fallback.get("zh", ""), "en": fallback.get("en", "")}
        source = fallback.get("source", "")

    body = pick(text_field, lang)

    if not include_header:
        return body

    label = "背景知识（仅供参考）" if lang == "zh" else "BACKGROUND KNOWLEDGE (for reference only)"
    src_label = "来源" if lang == "zh" else "Source"
    block = f"=== {label} ===\n{body}\n({src_label}: {source})"

    if include_related and card is not None and card.get("related_cards"):
        related_label = "相关背景" if lang == "zh" else "Related background"
        related_parts = []
        for rel_id in card["related_cards"]:
            rel_card = _find_card_by_id(scenario_cfg, rel_id)
            if rel_card:
                rel_body = pick(rel_card["text"], lang)
                rel_source = rel_card.get("source", "")
                related_parts.append(f"- {rel_body} ({src_label}: {rel_source})")
        if related_parts:
            block += f"\n\n[{related_label}]\n" + "\n".join(related_parts)

    return block


if __name__ == "__main__":
    knowledge = load_stance_knowledge()

    print("--- hit a topic card (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "parent_centered", "我们俩总是有冲突", lang="zh", knowledge=knowledge))

    print("\n--- no keyword match -> generic fallback (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "child_centered", "他说想学做饭", lang="zh", knowledge=knowledge))

    print("\n--- English, topic card (parent_child) ---")
    print(get_stance_knowledge_block(
        "parent_child", "relationship_centered", "I don't think he trusts me anymore", lang="en", knowledge=knowledge))

    print("\n--- employment scenario now has content too ---")
    print(get_stance_knowledge_block(
        "employment", "stability_centered", "我担心公司要裁员了", lang="zh", knowledge=knowledge))

    print("\n--- one-hop related_cards expansion ---")
    print(get_stance_knowledge_block(
        "employment", "growth_centered", "感觉这份工作技能都要跟不上了", lang="zh",
        knowledge=knowledge, include_related=True))

    print("\n--- scenario/stance combo with no cfg -> empty string (sanity check) ---")
    print(repr(get_stance_knowledge_block("employment", "nonexistent_stance", "anything", knowledge=knowledge)))
